title: Patrycjusz Blaszczuk's Tech Blog
description: > # this means to ignore newlines until "baseurl:"
  Blog about Android and Kotlin Multiplatform development, featuring new technologies like Jetpack Compose
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blaszcz.uk" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Patrycjusz Blaszczuk
author-img: me.jpeg # add your photo
about-author: Android Developer exploring Kotlin Multiplatform world.  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: solidogen # add your Github handle
social-linkedin: androiddevno999 # add your Linkedin handle
social-email: patrycjusz.blaszczuk@gmail.com # add your Email address

# Disqus
discus-identifier: solidogen # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
